### ISSUE TITLE
Использование engine вместо session

### ISSUE THREAD

**Issue by dmkovtun** [groupbwt/scrapy-command-new#12]
Перевести command-new на использование engine вместо session для работы с бд.

**Comment by KristobalJunta** [comment]
@DmitryKovtun чтобы перейти на sqlalchemy-core в запросах?

**Comment by dmkovtun** [comment]
@KristobalJunta из того, что знаю сам - из сессии не всегда свежие данные берет. А issue - чтобы не забыть. @tyorn  в mr указал на использование session и что это нужно когда-то менять в шаблонах.

**Comment by KristobalJunta** [comment]
Да, есть такое. Понял, спасибо.
